# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'nodejs'
#     static_configs:
#       - targets: ['localhost:3000']

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
    - targets: ['host.docker.internal:3000']
     

